<?php
    include_once('partial/header.php');
?>

<!-- contact  -->
<style>

.hide{
    height:0px;
    overflow: hidden;
    transition:height 0.7s ease-in-out;
}
.myDiv:hover+.hide{
    height:300px;
}
</style>
    <div class="customer_page container">
        <h3 class="font size text-center">Shop</h3>
            <h5 class="font size bold" id="about_shop">About Shop</h5>
            <div class="eachContainer">
                <div class="insideEach">
                    
                        Launched in 2012, Shop is South Asia's online shopping and selling destination of choice – present in Pakistan, Bangladesh, Sri Lanka, Myanmar and Nepal. Supported by a wide range of tailored marketing, data, and service solutions, the pioneering ecommerce ecosystem in South Asia has 30,000 sellers and 500 brands, serving 5 million consumers. With 2 million products available, Shop offers a diverse assortment of products in categories ranging from consumer electronics to household goods, beauty, fashion, sports equipment, and groceries. Focused on providing an excellent customer experience, it offers multiple payment methods including cash-on-delivery, comprehensive customer care and hassle-free returns.
                        Shop is owned by Alibaba Group Holding Limited.
                    
                </div>
            </div>

            <h5 class="font size bold" id="careers">Careers</h5>
            <div class="eachContainer">
                <div class="insideEach">
                    <p>
                        I have made <span class="hl">stop watch, music player and auto complete projects</span> with javascript relate as DOM and then Food order project with PHP. I have a plan to make projects as much as I can. I want to be a <span class="hl">Web Developer and then Machiine Language Engineer(Artifical Intelligence) with Python this my dream Job.</span>
                    </p>
                </div>
            </div>

            <h5 class="font size bold" id="tandc">Terms and Conditions</h5>
            <div class="eachContainer">
                <div class="insideEach">
                    <p>
                        Please read the Terms and Conditions carefully before using Food-order.com 

                        This document is an electronic record in terms of Electronic Transactions Law of 2004 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Electronic Transactions Law of 2004 .
                        
                        This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                </div>
            </div>

            <h5 class="font size bold" id="pandc">Privacy and Confidentiality</h5>
            <div class="eachContainer">
                <div class="insideEach">
                    <p>
                        Welcome to the shop.com.mm website (the "Site") operated by E-Cart Internet Services. We respect your privacy and want to protect your personal information. To learn more, please read this Privacy Policy.

                        This Privacy Policy explains how we collect, use and (under certain conditions) disclose your personal information. This Privacy Policy also explains the steps we have taken to secure your personal information. Finally, this Privacy Policy explains your options regarding the collection, use and disclosure of your personal information. By visiting the Site directly or through another site, you accept the practices described in this Policy.
                        
                        Data protection is a matter of trust and your privacy is important to us. We shall therefore only use your name and other information which relates to you in the manner set out in this Privacy Policy. We will only collect information where it is necessary for us to do so and we will only collect information if it is relevant to our dealings with you.
                        
                        We will only keep your information for as long as we are either required to by law or as is relevant for the purposes for which it was collected.
                        
                        You can visit the Site and browse without having to provide personal details. During your visit to the Site you remain anonymous and at no time can we identify you unless you have an account on the Site and log on with your user name and password.
                        
                        
                    </p>
                    <div class="qandans">
                        <div style="color:royalblue" class="myDiv">Other uses of your Personal Information</div>
                        <div class='hide'>We may use your personal information for opinion and market research. Your details are anonymous and will only be used for statistical purposes. You can choose to opt out of this at any time. Any answers to surveys or opinion polls we may ask you to complete will not be forwarded on to third parties. Disclosing your email address is only necessary if you would like to take part in competitions. We save the answers to our surveys separately from your email address.

                            We may also send you other information about us, the Site, our other websites, our products, sales promotions, our newsletters, anything relating to other companies in our group or our business partners. If you would prefer not to receive any of this additional information as detailed in this paragraph (or any part of it) please click the 'unsubscribe' link in any email that we send to you. Within 7 working days (days which are neither (i) a Sunday, nor (ii) a public holiday anywhere in Myanmar) of receipt of your instruction we will cease to send you information as requested. If your instruction is unclear we will contact you for clarification.
                            
                            We may further anonymize data about users of the Site generally and use it for various purposes, including ascertaining the general location of the users and usage of certain aspects of the Site or a link contained in an email to those registered to receive them, and supplying that anonymized data to third parties such as publishers. However, that anonymized data will not be capable of identifying you personally.
                        </div>
                    </div>
                    <div class="qandans">
                            <div style="color:royalblue" class="myDiv">Third Parties and Links</div>
                            <div class='hide'>We may pass your details to other companies in our group. We may also pass your details to our agents and subcontractors to help us with any of our uses of your data set out in our Privacy Policy. For example, we may use third parties to assist us with delivering products to you, to help us to collect payments from you, to analyze data and to provide us with marketing or customer service assistance.

                                We may exchange information with third parties for the purposes of fraud protection and credit risk reduction. We may transfer our databases containing your personal information if we sell our business or part of it. Other than as set out in this Privacy Policy, we shall NOT sell or disclose your personal data to third parties without obtaining your prior consent unless this is necessary for the purposes set out in this Privacy Policy or unless we are required to do so by law. The Site may contain advertising of third parties and links to other sites or frames of other sites. Please be aware that we are not responsible for the privacy practices or content of those third parties or other sites, nor for any third party to whom we transfer your data in accordance with our Privacy Policy.
                                
                                
                            </div>
                    </div>
                    <div class="qandans">
                            <div style="color:royalblue" class="myDiv">Security</div>
                            <div class='hide'>We have in place appropriate technical and security measures to prevent unauthorized or unlawful access to or accidental loss of or destruction or damage to your information. When we collect data through the Site, we collect your personal details on a secure server. We use firewalls on our servers. Our security procedures mean that we may occasionally request proof of identity before we disclose personal information to you. You are responsible for protecting against unauthorized access to your password and to your computer.
                            </div>
                    </div>
                </div>
            </div>

            <h5 class="font size bold" id="contact_us">Contact Us</h5>
            <div class="eachContainer">
                <div class="insideEach">
                    <p class="hl">
                       Email    - kyawbobolin1995@gmail.com<br>
                       Phone    - +95 9 799 586 273<br>
                       Address  - No.(301),(12)Street,(10)Block,South Okkalapa,Yangon. 
                    </p>
                </div>
            </div>
    </div>
<!-- contact  -->

<?php
    include_once('partial/footer.php');
?>